package com.ret;

import java.util.List;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Borrower implements java.io.Serializable {

	static final long serialVersionUID = 1L;
	private java.lang.String firstName;
	private java.lang.String lastName;
	private java.lang.String ssn;
	private java.util.List<com.ret.CreditScore> creditScores;
	private java.lang.Character borrowerType;
	private List<Employment> employmentList;
	private List<Liability> liabilities;
	public java.lang.String getFirstName() {
		return firstName;
	}
	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}
	public java.lang.String getLastName() {
		return lastName;
	}
	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}
	public java.lang.String getSsn() {
		return ssn;
	}
	public void setSsn(java.lang.String ssn) {
		this.ssn = ssn;
	}
	public java.util.List<com.ret.CreditScore> getCreditScores() {
		return creditScores;
	}
	public void setCreditScores(java.util.List<com.ret.CreditScore> creditScores) {
		this.creditScores = creditScores;
	}
	public java.lang.Character getBorrowerType() {
		return borrowerType;
	}
	public void setBorrowerType(java.lang.Character borrowerType) {
		this.borrowerType = borrowerType;
	}
	public List<Employment> getEmploymentList() {
		return employmentList;
	}
	public void setEmploymentList(List<Employment> employmentList) {
		this.employmentList = employmentList;
	}
	public List<Liability> getLiabilities() {
		return liabilities;
	}
	public void setLiabilities(List<Liability> liabilities) {
		this.liabilities = liabilities;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((borrowerType == null) ? 0 : borrowerType.hashCode());
		result = prime * result + ((creditScores == null) ? 0 : creditScores.hashCode());
		result = prime * result + ((employmentList == null) ? 0 : employmentList.hashCode());
		result = prime * result + ((firstName == null) ? 0 : firstName.hashCode());
		result = prime * result + ((lastName == null) ? 0 : lastName.hashCode());
		result = prime * result + ((liabilities == null) ? 0 : liabilities.hashCode());
		result = prime * result + ((ssn == null) ? 0 : ssn.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Borrower other = (Borrower) obj;
		if (borrowerType == null) {
			if (other.borrowerType != null)
				return false;
		} else if (!borrowerType.equals(other.borrowerType))
			return false;
		if (creditScores == null) {
			if (other.creditScores != null)
				return false;
		} else if (!creditScores.equals(other.creditScores))
			return false;
		if (employmentList == null) {
			if (other.employmentList != null)
				return false;
		} else if (!employmentList.equals(other.employmentList))
			return false;
		if (firstName == null) {
			if (other.firstName != null)
				return false;
		} else if (!firstName.equals(other.firstName))
			return false;
		if (lastName == null) {
			if (other.lastName != null)
				return false;
		} else if (!lastName.equals(other.lastName))
			return false;
		if (liabilities == null) {
			if (other.liabilities != null)
				return false;
		} else if (!liabilities.equals(other.liabilities))
			return false;
		if (ssn == null) {
			if (other.ssn != null)
				return false;
		} else if (!ssn.equals(other.ssn))
			return false;
		return true;
	}
	
	

}