package com.ret;

import java.time.LocalDate;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MIApplication implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String loanNumber;

	private java.lang.String ausResponse;

	private java.lang.String ausType;

	private java.lang.Integer ficoScore;

	private java.lang.String underwritingProgType;

	private LocalDate submissionDate;

	private java.lang.String propertyType;

	private java.lang.String loanType;

	private Double loanAmount;

	private Double propertyValue;

	private Double totalIncome;

	private Double totalDebt;

	private Double ltv;

	private Double dti;

	private java.lang.String occupancyType;

	private java.util.List<com.ret.Borrower> borrowers;

	public java.lang.String getLoanNumber() {
		return loanNumber;
	}

	public void setLoanNumber(java.lang.String loanNumber) {
		this.loanNumber = loanNumber;
	}

	public java.lang.String getAusResponse() {
		return ausResponse;
	}

	public void setAusResponse(java.lang.String ausResponse) {
		this.ausResponse = ausResponse;
	}

	public java.lang.String getAusType() {
		return ausType;
	}

	public void setAusType(java.lang.String ausType) {
		this.ausType = ausType;
	}

	public java.lang.Integer getFicoScore() {
		return ficoScore;
	}

	public void setFicoScore(java.lang.Integer ficoScore) {
		this.ficoScore = ficoScore;
	}

	public java.lang.String getUnderwritingProgType() {
		return underwritingProgType;
	}

	public void setUnderwritingProgType(java.lang.String underwritingProgType) {
		this.underwritingProgType = underwritingProgType;
	}

	public LocalDate getSubmissionDate() {
		return submissionDate;
	}

	public void setSubmissionDate(LocalDate submissionDate) {
		this.submissionDate = submissionDate;
	}

	public java.lang.String getPropertyType() {
		return propertyType;
	}

	public void setPropertyType(java.lang.String propertyType) {
		this.propertyType = propertyType;
	}

	public java.lang.String getLoanType() {
		return loanType;
	}

	public void setLoanType(java.lang.String loanType) {
		this.loanType = loanType;
	}

	public Double getLoanAmount() {
		return loanAmount;
	}

	public void setLoanAmount(Double loanAmount) {
		this.loanAmount = loanAmount;
	}

	public Double getPropertyValue() {
		return propertyValue;
	}

	public void setPropertyValue(Double propertyValue) {
		this.propertyValue = propertyValue;
	}

	public Double getTotalIncome() {
		return totalIncome;
	}

	public void setTotalIncome(Double totalIncome) {
		this.totalIncome = totalIncome;
	}

	public Double getTotalDebt() {
		return totalDebt;
	}

	public void setTotalDebt(Double totalDebt) {
		this.totalDebt = totalDebt;
	}

	public Double getLtv() {
		return ltv;
	}

	public void setLtv(Double ltv) {
		this.ltv = ltv;
	}

	public Double getDti() {
		return dti;
	}

	public void setDti(Double dti) {
		this.dti = dti;
	}

	public java.lang.String getOccupancyType() {
		return occupancyType;
	}

	public void setOccupancyType(java.lang.String occupancyType) {
		this.occupancyType = occupancyType;
	}

	public java.util.List<com.ret.Borrower> getBorrowers() {
		return borrowers;
	}

	public void setBorrowers(java.util.List<com.ret.Borrower> borrowers) {
		this.borrowers = borrowers;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ausResponse == null) ? 0 : ausResponse.hashCode());
		result = prime * result + ((ausType == null) ? 0 : ausType.hashCode());
		result = prime * result + ((borrowers == null) ? 0 : borrowers.hashCode());
		result = prime * result + ((dti == null) ? 0 : dti.hashCode());
		result = prime * result + ((ficoScore == null) ? 0 : ficoScore.hashCode());
		result = prime * result + ((loanAmount == null) ? 0 : loanAmount.hashCode());
		result = prime * result + ((loanNumber == null) ? 0 : loanNumber.hashCode());
		result = prime * result + ((loanType == null) ? 0 : loanType.hashCode());
		result = prime * result + ((ltv == null) ? 0 : ltv.hashCode());
		result = prime * result + ((occupancyType == null) ? 0 : occupancyType.hashCode());
		result = prime * result + ((propertyType == null) ? 0 : propertyType.hashCode());
		result = prime * result + ((propertyValue == null) ? 0 : propertyValue.hashCode());
		result = prime * result + ((submissionDate == null) ? 0 : submissionDate.hashCode());
		result = prime * result + ((totalDebt == null) ? 0 : totalDebt.hashCode());
		result = prime * result + ((totalIncome == null) ? 0 : totalIncome.hashCode());
		result = prime * result + ((underwritingProgType == null) ? 0 : underwritingProgType.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		MIApplication other = (MIApplication) obj;
		if (ausResponse == null) {
			if (other.ausResponse != null)
				return false;
		} else if (!ausResponse.equals(other.ausResponse))
			return false;
		if (ausType == null) {
			if (other.ausType != null)
				return false;
		} else if (!ausType.equals(other.ausType))
			return false;
		if (borrowers == null) {
			if (other.borrowers != null)
				return false;
		} else if (!borrowers.equals(other.borrowers))
			return false;
		if (dti == null) {
			if (other.dti != null)
				return false;
		} else if (!dti.equals(other.dti))
			return false;
		if (ficoScore == null) {
			if (other.ficoScore != null)
				return false;
		} else if (!ficoScore.equals(other.ficoScore))
			return false;
		if (loanAmount == null) {
			if (other.loanAmount != null)
				return false;
		} else if (!loanAmount.equals(other.loanAmount))
			return false;
		if (loanNumber == null) {
			if (other.loanNumber != null)
				return false;
		} else if (!loanNumber.equals(other.loanNumber))
			return false;
		if (loanType == null) {
			if (other.loanType != null)
				return false;
		} else if (!loanType.equals(other.loanType))
			return false;
		if (ltv == null) {
			if (other.ltv != null)
				return false;
		} else if (!ltv.equals(other.ltv))
			return false;
		if (occupancyType == null) {
			if (other.occupancyType != null)
				return false;
		} else if (!occupancyType.equals(other.occupancyType))
			return false;
		if (propertyType == null) {
			if (other.propertyType != null)
				return false;
		} else if (!propertyType.equals(other.propertyType))
			return false;
		if (propertyValue == null) {
			if (other.propertyValue != null)
				return false;
		} else if (!propertyValue.equals(other.propertyValue))
			return false;
		if (submissionDate == null) {
			if (other.submissionDate != null)
				return false;
		} else if (!submissionDate.equals(other.submissionDate))
			return false;
		if (totalDebt == null) {
			if (other.totalDebt != null)
				return false;
		} else if (!totalDebt.equals(other.totalDebt))
			return false;
		if (totalIncome == null) {
			if (other.totalIncome != null)
				return false;
		} else if (!totalIncome.equals(other.totalIncome))
			return false;
		if (underwritingProgType == null) {
			if (other.underwritingProgType != null)
				return false;
		} else if (!underwritingProgType.equals(other.underwritingProgType))
			return false;
		return true;
	}
	
	

}